name: docker-deploy

on:
  push:
    branches:
      - main

  # workflow_dispatch allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    env:
      GOFLAGS: ""
      GOPROXY: ""
    strategy:
      matrix:
        goversion: [1.16.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.goversion }}

      - name: Install protoc
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
                curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.5/protoc-3.15.5-linux-x86_64.zip
                unzip protoc-3.15.5-linux-x86_64.zip -d $HOME/.local
          elif [ "$RUNNER_OS" == "macOS" ]; then
                curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.5/protoc-3.15.5-osx-x86_64.zip
                unzip protoc-3.15.5-osx-x86_64.zip -d $HOME/.local
          else
                echo "$RUNNER_OS not supported"
                exit 1
          fi
          $HOME/.local/bin/protoc --version
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile proto
        run: |
          go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
          go get -u google.golang.org/grpc
          make proto

      - name: Build
        run: make build

      - name: Docker login, build and push
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          make pack
          make push
